### ISSUE TITLE
Fail to run with Seurat v3/Magic v2

### ISSUE THREAD

**Issue by ToledoEM** [Zhangxf-ccnu/EnImpute#2]
For a tool depending of many tools it need to be keep updated to be useful.

1.  With Seurat updated to version 3 it fail to run due to deprecated options in 'CreateSeuratObject' part.
```
Error in Seurat::CreateSeuratObject(count, normalization.method = "LogNormalize") : 
  unused argument (normalization.method = "LogNormalize")`
```
2. Magic fail with 

```
Argument k is deprecated. Using knn instead.
Argument alpha is deprecated. Using decay instead.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'knn_max'
```

3. I can't make it work with dca. This might be me.
```
library(reticulate)
conda_list(conda = "$APATH/anaconda3/condabin/conda") 
system("conda activate DCA")
use_condaenv(condaenv = "DCA",conda = "$APATH/anaconda3/condabin/conda",required = F)
conda_python(envname = "DCA", conda = "$APATH/anaconda3/condabin/conda")
```

With ` system('which dca')` I get `$APATH/anaconda3/bin/dca`

But executing it
```
$APATH/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
$APATH/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "$APATH/anaconda3/bin/dca", line 10, in <module>
    sys.exit(main())
  File "$APATH/anaconda3/lib/python3.7/site-packages/dca/__main__.py", line 147, in main
    from . import train
  File "$APATH/anaconda3/lib/python3.7/site-packages/dca/train.py", line 23, in <module>
    from . import io
  File "$APATH/anaconda3/lib/python3.7/site-packages/dca/io.py", line 24, in <module>
    import scipy as sp
  File "$APATH/anaconda3/lib/python3.7/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "$APATH/anaconda3/lib/python3.7/site-packages/scipy/fft/__init__.py", line 81, in <module>
    from ._helper import next_fast_len
  File "$APATH/anaconda3/lib/python3.7/site-packages/scipy/fft/_helper.py", line 4, in <module>
    from . import _pocketfft
  File "$APATH/anaconda3/lib/python3.7/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "$APATH/anaconda3/lib/python3.7/site-packages/scipy/fft/_pocketfft/basic.py", line 8, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by $APATH/anaconda3/lib/python3.7/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-37m-x86_64-linux-gnu.so)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './DCA_result/result/mean.tsv': No such file or directory

```

**Comment by Rohit-Satyam** [comment]
I made some amends in the code here: https://github.com/Rohit-Satyam/EnImpute/tree/master. In case if you are still interested, please have a look. I am still resolving errors so I will be updating the code in coming weeks,
